kind: Deployment
apiVersion: apps/v1
metadata:
  name: snapshotweb-v1
  namespace: infrastructure
  labels:
    app: snapshotweb-v1
  annotations:
    deployment.kubernetes.io/revision: '5'
    kubesphere.io/creator: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapshotweb-v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snapshotweb-v1
      annotations:
        kubesphere.io/creator: admin
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      volumes:
        - name: volume-ccv78d
          persistentVolumeClaim:
            claimName: snapshotweb
        - name: volume-7b7g8m
          persistentVolumeClaim:
            claimName: snapshotweb-db
      containers:
        - name: container-6a6bsu
          image: 'tomassky/snapshotweb-v1:latest'
          ports:
            - name: http-0
              containerPort: 5000
              protocol: TCP
          env:
            - name: BOTTOKEN
              valueFrom:
                secretKeyRef:
                  name: tg-bot-token
                  key: BOTTOKEN
          resources: {}
          volumeMounts:
            - name: volume-ccv78d
              mountPath: /root/snapshotWeb/mhtmlfiles
            - name: volume-7b7g8m
              mountPath: /root/snapshotWeb/db
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
