apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infrastructure
  name: snapshotweb-db
  labels: {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
